name: Cross-Platform Build

on:
  workflow_dispatch:
  push:
    paths:
      - love_heart.py

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create And Upload Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'love_heart.py'
          upload_exe_with_name: 'love_heart_windows'
          options: --onefile --name "love_heart" --windowed

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Create Executable
        run: pyinstaller --onefile --name "love_heart_linux" love_heart.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: love_heart_linux
          path: dist/love_heart_linux
